name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      # with:
      #   ruby-version: '2.6' 
    - run: ruby -v
    - run: apt install hugo
